package com.foda.rca.model;

import lombok.Builder;
import lombok.Value;

import java.util.List;

/**
 * A ranked root-cause candidate produced by the <em>Ranking Layer</em> (Section 3.4).
 *
 * <p>Each {@code RankedCause} bundles the final propagated confidence score
 * {@code C(s)} with the complete diagnostic evidence trail, making the result
 * fully auditable for both operators and peer reviewers.</p>
 */
@Value
@Builder
public class RankedCause {

    /** Rank position in the ordered list (1-based; 1 = most likely root cause). */
    int rank;

    /** Service identified as a root-cause candidate. */
    String serviceId;

    /**
     * Final aggregated confidence C(s) ∈ [0, 1] after propagation.
     *
     * <p>Computed via probabilistic OR (noisy-OR) aggregation:
     * <pre>C(s) = 1 – (1 – H(s)) × ∏_{u ∈ pred(s)} (1 – C(u) × w(u,s))</pre>
     * where H(s) is the local hypothesis confidence and w(u,s) is the edge weight.</p>
     */
    double finalConfidence;

    /**
     * Local fault confidence H(s) ∈ [0, 1] from the inference layer alone
     * (before upstream propagation is added).
     */
    double localConfidence;

    /**
     * Confidence contributed solely by upstream propagation P(s) ∈ [0, 1].
     * <pre>P(s) = 1 – ∏_{u ∈ pred(s)} (1 – C(u) × w(u,s))</pre>
     */
    double propagatedConfidence;

    /** Dominant fault category inferred for this service. */
    String faultCategory;

    /**
     * Ordered list of service IDs forming the highest-confidence causal path
     * leading to this root cause (e.g., ["gateway", "payment-service", "db-service"]).
     */
    List<String> causalPath;

    /** Human-readable NL explanation generated by the Explanation Layer (Section 3.5). */
    String explanation;
}
